const y8Urls = {
  '/y8-studio/unity/akeemywka/impossible_bike_stunts_3d/': 'https://www.y8.com/games/impossible_bike_stunt_3d',
  '/y8-studio/unity/akeemywka/impossible_bike_stunts_3d/index.html': 'https://www.y8.com/games/impossible_bike_stunt_3d',
  '/y8-studio/unity/akeemywka/last_resistance_city_under_siege/': 'https://www.y8.com/games/last_resistance_-_city_under_siege',
  '/y8-studio/unity/akeemywka/last_resistance_city_under_siege/index.html': 'https://www.y8.com/games/last_resistance_-_city_under_siege',
  '/y8-studio/unity/akeemywka/moto_trials_winter/': 'https://www.y8.com/games/moto_trials_winter',
  '/y8-studio/unity/akeemywka/moto_trials_winter/index.html': 'https://www.y8.com/games/moto_trials_winter',
  '/y8-studio/unity/akeemywka/moto_trials_winter_2/': 'https://www.y8.com/games/moto_trials_winter_2',
  '/y8-studio/unity/akeemywka/moto_trials_winter_2/index.html': 'https://www.y8.com/games/moto_trials_winter_2',
  '/y8-studio/unity/akeemywka/russian_extreme_offroad/': 'https://www.y8.com/games/russian_extreme_offroad',
  '/y8-studio/unity/akeemywka/russian_extreme_offroad/index.html': 'https://www.y8.com/games/russian_extreme_offroad',
  '/y8-studio/unity/akeemywka/taz_mechanic_simulator/': 'https://www.y8.com/games/taz_mechanic_simulator',
  '/y8-studio/unity/akeemywka/taz_mechanic_simulator/index.html': 'https://www.y8.com/games/taz_mechanic_simulator',
  '/y8-studio/unity/akeemywka/voxel_front_3d/': 'https://www.y8.com/games/voxel_front_3d',
  '/y8-studio/unity/akeemywka/voxel_front_3d/index.html': 'https://www.y8.com/games/voxel_front_3d',
  '/y8-studio/unity/joll/crime_city_3d/': 'https://www.y8.com/games/crime_city_3d',
  '/y8-studio/unity/joll/crime_city_3d/index.html': 'https://www.y8.com/games/crime_city_3d',
  '/y8-studio/unity/joll/russian_car_driver_hd/': 'https://www.y8.com/games/russian_car_driver_hd',
  '/y8-studio/unity/joll/russian_car_driver_hd/index.html': 'https://www.y8.com/games/russian_car_driver_hd',
  '/y8-studio/unity/joll/slope/': 'https://www.y8.com/games/slope',
  '/y8-studio/unity/joll/slope/index.html': 'https://www.y8.com/games/slope',
}
